-- ===========================================================================
-- Populate US News rankings by IPEDS ID (scorecard_id)
-- Also inserts colleges not yet in the database
-- ===========================================================================

-- Helper: upsert rankings via a temp table
CREATE TEMP TABLE _rankings (
    scorecard_id      integer PRIMARY KEY,
    school_name       text NOT NULL,
    slug              text NOT NULL,
    national_rank     integer,
    business_rank     integer,
    liberal_arts_rank integer,
    city              text,
    state_region      text,
    website_url       text,
    app_platform      text
);

INSERT INTO _rankings (scorecard_id, school_name, slug, national_rank, business_rank, liberal_arts_rank, city, state_region, website_url, app_platform) VALUES
-- National University Rankings (25 formerly-seeded schools include city/state/website/platform)
(186131, 'Princeton University', 'princeton-university', 1, NULL, NULL, 'Princeton', 'NJ', 'https://www.princeton.edu', 'Common App'),
(166683, 'Massachusetts Institute of Technology', 'mit', 2, 1, NULL, 'Cambridge', 'MA', 'https://www.mit.edu', 'MyMIT'),
(166027, 'Harvard University', 'harvard-university', 3, NULL, NULL, 'Cambridge', 'MA', 'https://www.harvard.edu', 'Common App'),
(243744, 'Stanford University', 'stanford-university', 4, NULL, NULL, 'Stanford', 'CA', 'https://www.stanford.edu', 'Common App'),
(130794, 'Yale University', 'yale-university', 4, NULL, NULL, 'New Haven', 'CT', 'https://www.yale.edu', 'Common App'),
(144050, 'University of Chicago', 'university-of-chicago', 6, NULL, NULL, 'Chicago', 'IL', 'https://www.uchicago.edu', 'Common App'),
(198419, 'Duke University', 'duke-university', 7, NULL, NULL, 'Durham', 'NC', 'https://www.duke.edu', 'Common App'),
(162928, 'Johns Hopkins University', 'johns-hopkins-university', 7, NULL, NULL, NULL, NULL, NULL, NULL),
(147767, 'Northwestern University', 'northwestern-university', 7, NULL, NULL, 'Evanston', 'IL', 'https://www.northwestern.edu', 'Common App'),
(215062, 'University of Pennsylvania', 'university-of-pennsylvania', 7, 1, NULL, 'Philadelphia', 'PA', 'https://www.upenn.edu', 'Common App'),
(110404, 'California Institute of Technology', 'caltech', 11, NULL, NULL, NULL, NULL, NULL, NULL),
(190415, 'Cornell University', 'cornell-university', 12, 8, NULL, 'Ithaca', 'NY', 'https://www.cornell.edu', 'Common App'),
(217156, 'Brown University', 'brown-university', 13, NULL, NULL, 'Providence', 'RI', 'https://www.brown.edu', 'Common App'),
(182670, 'Dartmouth College', 'dartmouth-college', 13, NULL, NULL, 'Hanover', 'NH', 'https://www.dartmouth.edu', 'Common App'),
(190150, 'Columbia University', 'columbia-university', 15, NULL, NULL, 'New York', 'NY', 'https://www.columbia.edu', 'Common App'),
(110635, 'University of California, Berkeley', 'uc-berkeley', 15, 3, NULL, 'Berkeley', 'CA', 'https://www.berkeley.edu', 'UC App'),
(110662, 'University of California, Los Angeles', 'ucla', 17, NULL, NULL, 'Los Angeles', 'CA', 'https://www.ucla.edu', 'UC App'),
(227757, 'Rice University', 'rice-university', 17, 24, NULL, 'Houston', 'TX', 'https://www.rice.edu', 'Common App'),
(221999, 'Vanderbilt University', 'vanderbilt-university', 17, NULL, NULL, 'Nashville', 'TN', 'https://www.vanderbilt.edu', 'Common App'),
(152080, 'University of Notre Dame', 'university-of-notre-dame', 20, 12, NULL, 'Notre Dame', 'IN', 'https://www.nd.edu', 'Common App'),
(211440, 'Carnegie Mellon University', 'carnegie-mellon-university', 20, 6, NULL, NULL, NULL, NULL, NULL),
(170976, 'University of Michigan', 'university-of-michigan', 20, 4, NULL, 'Ann Arbor', 'MI', 'https://umich.edu', 'Common App'),
(179867, 'Washington University in St. Louis', 'washington-university-st-louis', 20, 12, NULL, NULL, NULL, NULL, NULL),
(139658, 'Emory University', 'emory-university', 24, 12, NULL, 'Atlanta', 'GA', 'https://www.emory.edu', 'Common App'),
(131496, 'Georgetown University', 'georgetown-university', 24, 12, NULL, 'Washington', 'DC', 'https://www.georgetown.edu', 'Georgetown App'),
(234076, 'University of Virginia', 'university-of-virginia', 26, 12, NULL, 'Charlottesville', 'VA', 'https://www.virginia.edu', 'Common App'),
(199120, 'University of North Carolina at Chapel Hill', 'unc-chapel-hill', 26, 8, NULL, NULL, NULL, NULL, NULL),
(123961, 'University of Southern California', 'usc', 28, 8, NULL, 'Los Angeles', 'CA', 'https://www.usc.edu', 'Common App'),
(110680, 'University of California, San Diego', 'uc-san-diego', 29, 51, NULL, NULL, NULL, NULL, NULL),
(134130, 'University of Florida', 'university-of-florida', 30, 24, NULL, NULL, NULL, NULL, NULL),
(228778, 'University of Texas at Austin', 'ut-austin', 30, 6, NULL, NULL, NULL, NULL, NULL),
(193900, 'New York University', 'nyu', 32, 5, NULL, 'New York', 'NY', 'https://www.nyu.edu', 'Common App'),
(139755, 'Georgia Institute of Technology', 'georgia-tech', 32, NULL, NULL, NULL, NULL, NULL, NULL),
(110644, 'University of California, Davis', 'uc-davis', 32, NULL, NULL, NULL, NULL, NULL, NULL),
(110653, 'University of California, Irvine', 'uc-irvine', 32, 32, NULL, NULL, NULL, NULL, NULL),
(145637, 'University of Illinois Urbana-Champaign', 'uiuc', 36, 12, NULL, NULL, NULL, NULL, NULL),
(164924, 'Boston College', 'boston-college', 36, 32, NULL, NULL, NULL, NULL, NULL),
(168148, 'Tufts University', 'tufts-university', 36, NULL, NULL, NULL, NULL, NULL, NULL),
(240444, 'University of Wisconsin-Madison', 'uw-madison', 36, 19, NULL, NULL, NULL, NULL, NULL),
(110705, 'University of California, Santa Barbara', 'uc-santa-barbara', 40, NULL, NULL, NULL, NULL, NULL, NULL),
(204796, 'Ohio State University', 'ohio-state-university', 40, 12, NULL, NULL, NULL, NULL, NULL),
(164988, 'Boston University', 'boston-university', 42, 37, NULL, 'Boston', 'MA', 'https://www.bu.edu', 'Common App'),
(186380, 'Rutgers University-New Brunswick', 'rutgers-new-brunswick', 42, 77, NULL, NULL, NULL, NULL, NULL),
(163286, 'University of Maryland, College Park', 'umd-college-park', 42, 24, NULL, NULL, NULL, NULL, NULL),
(236948, 'University of Washington', 'university-of-washington', 42, NULL, NULL, NULL, NULL, NULL, NULL),
(195030, 'University of Rochester', 'university-of-rochester', 46, 51, NULL, NULL, NULL, NULL, NULL),
(213543, 'Lehigh University', 'lehigh-university', 46, 77, NULL, NULL, NULL, NULL, NULL),
(243780, 'Purdue University', 'purdue-university', 46, 24, NULL, NULL, NULL, NULL, NULL),
(139959, 'University of Georgia', 'university-of-georgia', 46, 19, NULL, NULL, NULL, NULL, NULL),
(167358, 'Northeastern University', 'northeastern-university', 46, 64, NULL, NULL, NULL, NULL, NULL),
(199847, 'Wake Forest University', 'wake-forest-university', 51, 41, NULL, NULL, NULL, NULL, NULL),
(201645, 'Case Western Reserve University', 'case-western-reserve', 51, 41, NULL, NULL, NULL, NULL, NULL),
(228723, 'Texas A&M University', 'texas-am-university', 51, NULL, NULL, NULL, NULL, NULL, NULL),
(233921, 'Virginia Tech', 'virginia-tech', 51, 51, NULL, NULL, NULL, NULL, NULL),
(231624, 'College of William and Mary', 'william-and-mary', 51, NULL, NULL, NULL, NULL, NULL, NULL),
(134097, 'Florida State University', 'florida-state-university', 51, 51, NULL, NULL, NULL, NULL, NULL),
(445188, 'University of California, Merced', 'uc-merced', 57, NULL, NULL, NULL, NULL, NULL, NULL),
(216597, 'Villanova University', 'villanova-university', 57, 51, NULL, NULL, NULL, NULL, NULL),
(174066, 'University of Minnesota', 'university-of-minnesota', 59, 19, NULL, NULL, NULL, NULL, NULL),
(196097, 'Stony Brook University', 'stony-brook-university', 59, 109, NULL, NULL, NULL, NULL, NULL),
(131469, 'George Washington University', 'george-washington-university', 59, 41, NULL, NULL, NULL, NULL, NULL),
(214777, 'Pennsylvania State University', 'penn-state', 59, 24, NULL, NULL, NULL, NULL, NULL),
(122931, 'Santa Clara University', 'santa-clara-university', 59, 64, NULL, NULL, NULL, NULL, NULL),
(199193, 'North Carolina State University', 'nc-state', 64, NULL, NULL, NULL, NULL, NULL, NULL),
(166629, 'University of Massachusetts Amherst', 'umass-amherst', 64, 64, NULL, NULL, NULL, NULL, NULL),
(171100, 'Michigan State University', 'michigan-state-university', 64, 24, NULL, NULL, NULL, NULL, NULL),
(135726, 'University of Miami', 'university-of-miami', 64, 41, NULL, NULL, NULL, NULL, NULL),
(194824, 'Rensselaer Polytechnic Institute', 'rensselaer-polytechnic', 64, 88, NULL, NULL, NULL, NULL, NULL),
(165015, 'Brandeis University', 'brandeis-university', 69, 88, NULL, NULL, NULL, NULL, NULL),
(160755, 'Tulane University', 'tulane-university', 69, 41, NULL, NULL, NULL, NULL, NULL),
(129020, 'University of Connecticut', 'university-of-connecticut', 69, 51, NULL, NULL, NULL, NULL, NULL),
(215293, 'University of Pittsburgh', 'university-of-pittsburgh', 69, 41, NULL, NULL, NULL, NULL, NULL),
(196079, 'Binghamton University', 'binghamton-university', 73, 109, NULL, NULL, NULL, NULL, NULL),
(151351, 'Indiana University Bloomington', 'indiana-university-bloomington', 73, 8, NULL, NULL, NULL, NULL, NULL),
(196413, 'Syracuse University', 'syracuse-university', 75, 51, NULL, NULL, NULL, NULL, NULL),
(196088, 'University at Buffalo', 'university-at-buffalo', 75, 88, NULL, NULL, NULL, NULL, NULL),
(110671, 'University of California, Riverside', 'uc-riverside', 75, 88, NULL, NULL, NULL, NULL, NULL),
(217882, 'Clemson University', 'clemson-university', 75, 64, NULL, NULL, NULL, NULL, NULL),
(186399, 'Rutgers University-Newark', 'rutgers-newark', 75, 109, NULL, NULL, NULL, NULL, NULL),
(126775, 'Colorado School of Mines', 'colorado-school-of-mines', 80, NULL, NULL, NULL, NULL, NULL, NULL),
(186867, 'Stevens Institute of Technology', 'stevens-institute', 80, NULL, NULL, NULL, NULL, NULL, NULL),
(185828, 'New Jersey Institute of Technology', 'njit', 80, NULL, NULL, NULL, NULL, NULL, NULL),
(212054, 'Drexel University', 'drexel-university', 80, 109, NULL, NULL, NULL, NULL, NULL),
(121150, 'Pepperdine University', 'pepperdine-university', 84, 64, NULL, NULL, NULL, NULL, NULL),
(145600, 'University of Illinois Chicago', 'uic', 84, 77, NULL, NULL, NULL, NULL, NULL),
(168421, 'Worcester Polytechnic Institute', 'wpi', 84, NULL, NULL, NULL, NULL, NULL, NULL),
(197708, 'Yeshiva University', 'yeshiva-university', 84, NULL, NULL, NULL, NULL, NULL, NULL),
(110714, 'University of California, Santa Cruz', 'uc-santa-cruz', 88, NULL, NULL, NULL, NULL, NULL, NULL),
(131520, 'Howard University', 'howard-university', 88, 88, NULL, NULL, NULL, NULL, NULL),
(239105, 'Marquette University', 'marquette-university', 88, 109, NULL, NULL, NULL, NULL, NULL),
(130943, 'University of Delaware', 'university-of-delaware', 88, 88, NULL, NULL, NULL, NULL, NULL),
(131159, 'American University', 'american-university', 88, 77, NULL, NULL, NULL, NULL, NULL),
(223232, 'Baylor University', 'baylor-university', 88, 64, NULL, NULL, NULL, NULL, NULL),
(195003, 'Rochester Institute of Technology', 'rochester-institute', 88, 77, NULL, NULL, NULL, NULL, NULL),
(228246, 'Southern Methodist University', 'southern-methodist-university', 88, 51, NULL, NULL, NULL, NULL, NULL),
(137351, 'University of South Florida', 'university-of-south-florida', 88, 109, NULL, NULL, NULL, NULL, NULL),
(191241, 'Fordham University', 'fordham-university', 97, 77, NULL, NULL, NULL, NULL, NULL),
(133951, 'Florida International University', 'fiu', 97, 109, NULL, NULL, NULL, NULL, NULL),
(186371, 'Rutgers University-Camden', 'rutgers-camden', 97, 131, NULL, NULL, NULL, NULL, NULL),
(126614, 'University of Colorado Boulder', 'university-of-colorado-boulder', 97, 32, NULL, NULL, NULL, NULL, NULL),
(228875, 'Texas Christian University', 'texas-christian-university', 97, 77, NULL, NULL, NULL, NULL, NULL),
(117946, 'Loyola Marymount University', 'loyola-marymount', 102, 88, NULL, NULL, NULL, NULL, NULL),
(235316, 'Gonzaga University', 'gonzaga-university', 102, 88, NULL, NULL, NULL, NULL, NULL),
(216339, 'Temple University', 'temple-university', 102, 88, NULL, NULL, NULL, NULL, NULL),
(153658, 'University of Iowa', 'university-of-iowa', 102, 32, NULL, NULL, NULL, NULL, NULL),
(100858, 'Auburn University', 'auburn-university', 102, 51, NULL, NULL, NULL, NULL, NULL),
(179159, 'Saint Louis University', 'saint-louis-university', 102, 109, NULL, NULL, NULL, NULL, NULL),
(178396, 'University of Missouri', 'university-of-missouri', 102, 64, NULL, NULL, NULL, NULL, NULL),
(221759, 'University of Tennessee, Knoxville', 'university-of-tennessee', 102, 37, NULL, NULL, NULL, NULL, NULL),
(230038, 'Brigham Young University', 'brigham-young-university', 110, 37, NULL, NULL, NULL, NULL, NULL),
(209551, 'University of Oregon', 'university-of-oregon', 110, 41, NULL, NULL, NULL, NULL, NULL),
(122436, 'University of San Diego', 'university-of-san-diego', 110, NULL, NULL, NULL, NULL, NULL, NULL),
(122612, 'University of San Francisco', 'university-of-san-francisco', 110, 131, NULL, NULL, NULL, NULL, NULL),
(228787, 'University of Texas at Dallas', 'ut-dallas', 110, 51, NULL, NULL, NULL, NULL, NULL),
(111948, 'Chapman University', 'chapman-university', 110, NULL, NULL, NULL, NULL, NULL, NULL),
(207500, 'University of Oklahoma', 'university-of-oklahoma', 110, NULL, NULL, NULL, NULL, NULL, NULL),
(145725, 'Illinois Institute of Technology', 'illinois-institute-of-technology', 117, NULL, NULL, NULL, NULL, NULL, NULL),
(232186, 'George Mason University', 'george-mason-university', 117, 88, NULL, NULL, NULL, NULL, NULL),
(122409, 'San Diego State University', 'san-diego-state-university', 117, 64, NULL, NULL, NULL, NULL, NULL),
(183044, 'University of New Hampshire', 'university-of-new-hampshire', 117, 131, NULL, NULL, NULL, NULL, NULL),
(104151, 'Arizona State University', 'arizona-state-university', 117, NULL, NULL, NULL, NULL, NULL, NULL),
(181002, 'Creighton University', 'creighton-university', 117, 88, NULL, NULL, NULL, NULL, NULL),
(198516, 'Elon University', 'elon-university', 117, NULL, NULL, NULL, NULL, NULL, NULL),
(153603, 'Iowa State University', 'iowa-state-university', 117, 109, NULL, NULL, NULL, NULL, NULL),
(132903, 'University of Central Florida', 'university-of-central-florida', 117, 109, NULL, NULL, NULL, NULL, NULL),
(127060, 'University of Denver', 'university-of-denver', 117, 88, NULL, NULL, NULL, NULL, NULL),
(110565, 'California State University, Long Beach', 'csu-long-beach', 127, NULL, NULL, NULL, NULL, NULL, NULL),
(104179, 'University of Arizona', 'university-of-arizona', 127, 32, NULL, NULL, NULL, NULL, NULL),
(196060, 'University at Albany', 'university-at-albany', 127, NULL, NULL, NULL, NULL, NULL, NULL),
(218663, 'University of South Carolina', 'university-of-south-carolina', 127, NULL, NULL, NULL, NULL, NULL, NULL),
(163268, 'University of Maryland, Baltimore County', 'umbc', 127, NULL, NULL, NULL, NULL, NULL, NULL),
(190567, 'CUNY City College', 'cuny-city-college', 132, 77, NULL, NULL, NULL, NULL, NULL),
(231174, 'University of Vermont', 'university-of-vermont', 132, 131, NULL, NULL, NULL, NULL, NULL),
(110583, 'California State University, Fullerton', 'csu-fullerton', 132, NULL, NULL, NULL, NULL, NULL, NULL),
(165334, 'Clark University', 'clark-university', 132, NULL, NULL, NULL, NULL, NULL, NULL),
(146719, 'Loyola University Chicago', 'loyola-university-chicago', 132, 77, NULL, NULL, NULL, NULL, NULL),
(216366, 'Thomas Jefferson University', 'thomas-jefferson-university', 132, NULL, NULL, NULL, NULL, NULL, NULL),
(100663, 'University of Alabama at Birmingham', 'uab', 132, 109, NULL, NULL, NULL, NULL, NULL),
(225511, 'University of Houston', 'university-of-houston', 132, 88, NULL, NULL, NULL, NULL, NULL),
(129242, 'Fairfield University', 'fairfield-university', 139, 131, NULL, NULL, NULL, NULL, NULL),
(120883, 'University of the Pacific', 'university-of-the-pacific', 139, NULL, NULL, NULL, NULL, NULL, NULL),
(234030, 'Virginia Commonwealth University', 'vcu', 139, 131, NULL, NULL, NULL, NULL, NULL),
(204024, 'Miami University-Oxford', 'miami-university-oxford', 143, 88, NULL, NULL, NULL, NULL, NULL),
(202480, 'University of Dayton', 'university-of-dayton', 143, NULL, NULL, NULL, NULL, NULL, NULL),
(209542, 'Oregon State University', 'oregon-state-university', 143, 109, NULL, NULL, NULL, NULL, NULL),
(190044, 'Clarkson University', 'clarkson-university', 143, NULL, NULL, NULL, NULL, NULL, NULL),
(155317, 'University of Kansas', 'university-of-kansas', 143, 64, NULL, NULL, NULL, NULL, NULL),
(157085, 'University of Kentucky', 'university-of-kentucky', 143, 64, NULL, NULL, NULL, NULL, NULL),
(199139, 'University of North Carolina at Charlotte', 'unc-charlotte', 143, 131, NULL, NULL, NULL, NULL, NULL),
(196592, 'Touro University', 'touro-university', 143, NULL, NULL, NULL, NULL, NULL, NULL),
-- Liberal Arts College Rankings
(168342, 'Williams College', 'williams-college', NULL, NULL, 1, NULL, NULL, NULL, NULL),
(164465, 'Amherst College', 'amherst-college', NULL, NULL, 2, NULL, NULL, NULL, NULL),
(164155, 'United States Naval Academy', 'us-naval-academy', NULL, NULL, 3, NULL, NULL, NULL, NULL),
(216287, 'Swarthmore College', 'swarthmore-college', NULL, NULL, 4, NULL, NULL, NULL, NULL),
(161004, 'Bowdoin College', 'bowdoin-college', NULL, NULL, 5, NULL, NULL, NULL, NULL),
(128328, 'United States Air Force Academy', 'us-air-force-academy', NULL, 64, 6, NULL, NULL, NULL, NULL),
(121345, 'Pomona College', 'pomona-college', NULL, NULL, 7, NULL, NULL, NULL, NULL),
(168218, 'Wellesley College', 'wellesley-college', NULL, NULL, 8, NULL, NULL, NULL, NULL),
(112260, 'Claremont McKenna College', 'claremont-mckenna-college', NULL, NULL, 9, NULL, NULL, NULL, NULL),
(197036, 'United States Military Academy', 'us-military-academy', NULL, NULL, 10, NULL, NULL, NULL, NULL),
(173258, 'Carleton College', 'carleton-college', NULL, NULL, 11, NULL, NULL, NULL, NULL),
(115409, 'Harvey Mudd College', 'harvey-mudd-college', NULL, NULL, 12, NULL, NULL, NULL, NULL),
(197133, 'Vassar College', 'vassar-college', NULL, NULL, 13, NULL, NULL, NULL, NULL),
(189097, 'Barnard College', 'barnard-college', NULL, NULL, 14, NULL, NULL, NULL, NULL),
(130697, 'Wesleyan University', 'wesleyan-university', NULL, NULL, 15, NULL, NULL, NULL, NULL),
(198385, 'Davidson College', 'davidson-college', NULL, NULL, 16, NULL, NULL, NULL, NULL),
(191515, 'Hamilton College', 'hamilton-college', NULL, NULL, 17, NULL, NULL, NULL, NULL),
(167835, 'Smith College', 'smith-college', NULL, NULL, 18, NULL, NULL, NULL, NULL),
(153384, 'Grinnell College', 'grinnell-college', NULL, NULL, 19, NULL, NULL, NULL, NULL),
(230959, 'Middlebury College', 'middlebury-college', NULL, NULL, 20, NULL, NULL, NULL, NULL),
(234207, 'Washington and Lee University', 'washington-and-lee', NULL, 131, 21, NULL, NULL, NULL, NULL),
(190099, 'Colgate University', 'colgate-university', NULL, NULL, 22, NULL, NULL, NULL, NULL),
(233374, 'University of Richmond', 'university-of-richmond', NULL, 109, 23, NULL, NULL, NULL, NULL),
(212911, 'Haverford College', 'haverford-college', NULL, NULL, 24, NULL, NULL, NULL, NULL),
(161086, 'Colby College', 'colby-college', NULL, NULL, 25, NULL, NULL, NULL, NULL),
(160977, 'Bates College', 'bates-college', NULL, NULL, 26, NULL, NULL, NULL, NULL),
(166124, 'College of the Holy Cross', 'holy-cross', NULL, NULL, 27, NULL, NULL, NULL, NULL),
(173902, 'Macalester College', 'macalester-college', NULL, NULL, 28, NULL, NULL, NULL, NULL),
(166939, 'Mount Holyoke College', 'mount-holyoke-college', NULL, NULL, 29, NULL, NULL, NULL, NULL),
(126678, 'Colorado College', 'colorado-college', NULL, NULL, 30, NULL, NULL, NULL, NULL),
(211273, 'Bryn Mawr College', 'bryn-mawr-college', NULL, NULL, 31, NULL, NULL, NULL, NULL),
(211291, 'Bucknell University', 'bucknell-university', NULL, 131, 32, NULL, NULL, NULL, NULL),
(213385, 'Lafayette College', 'lafayette-college', NULL, NULL, 33, NULL, NULL, NULL, NULL),
(202523, 'Denison University', 'denison-university', NULL, NULL, 34, NULL, NULL, NULL, NULL),
(212577, 'Franklin and Marshall College', 'franklin-and-marshall', NULL, NULL, 35, NULL, NULL, NULL, NULL),
(120254, 'Occidental College', 'occidental-college', NULL, NULL, 36, NULL, NULL, NULL, NULL),
(195526, 'Skidmore College', 'skidmore-college', NULL, NULL, 37, NULL, NULL, NULL, NULL),
(121257, 'Pitzer College', 'pitzer-college', NULL, NULL, 38, NULL, NULL, NULL, NULL),
(130590, 'Trinity College', 'trinity-college-ct', NULL, NULL, 39, NULL, NULL, NULL, NULL),
(141060, 'Spelman College', 'spelman-college', NULL, NULL, 40, NULL, NULL, NULL, NULL),
(229267, 'Trinity University', 'trinity-university', NULL, NULL, 41, NULL, NULL, NULL, NULL),
(123165, 'Scripps College', 'scripps-college', NULL, NULL, 42, NULL, NULL, NULL, NULL),
(399911, 'Soka University of America', 'soka-university', NULL, NULL, 43, NULL, NULL, NULL, NULL),
(196866, 'Union College', 'union-college', NULL, NULL, 44, NULL, NULL, NULL, NULL),
(156295, 'Berea College', 'berea-college', NULL, NULL, 45, NULL, NULL, NULL, NULL),
(203535, 'Kenyon College', 'kenyon-college', NULL, NULL, 46, NULL, NULL, NULL, NULL),
(212009, 'Dickinson College', 'dickinson-college', NULL, NULL, 47, NULL, NULL, NULL, NULL),
(218070, 'Furman University', 'furman-university', NULL, NULL, 48, NULL, NULL, NULL, NULL),
(221519, 'Sewanee: The University of the South', 'sewanee', NULL, NULL, 49, NULL, NULL, NULL, NULL),
(170286, 'Hillsdale College', 'hillsdale-college', NULL, NULL, 50, NULL, NULL, NULL, NULL),
(174844, 'St. Olaf College', 'st-olaf-college', NULL, NULL, 51, NULL, NULL, NULL, NULL),
(149781, 'Wheaton College', 'wheaton-college-il', NULL, NULL, 52, NULL, NULL, NULL, NULL),
(128902, 'Connecticut College', 'connecticut-college', NULL, NULL, 53, NULL, NULL, NULL, NULL),
(152673, 'Wabash College', 'wabash-college', NULL, NULL, 54, NULL, NULL, NULL, NULL),
(156408, 'Centre College', 'centre-college', NULL, NULL, 55, NULL, NULL, NULL, NULL),
(221351, 'Rhodes College', 'rhodes-college', NULL, NULL, 56, NULL, NULL, NULL, NULL),
(124292, 'Thomas Aquinas College', 'thomas-aquinas-college', NULL, NULL, 57, NULL, NULL, NULL, NULL),
(150400, 'DePauw University', 'depauw-university', NULL, NULL, 58, NULL, NULL, NULL, NULL),
(237057, 'Whitman College', 'whitman-college', NULL, NULL, 59, NULL, NULL, NULL, NULL),
(204501, 'Oberlin College', 'oberlin-college', NULL, NULL, 60, NULL, NULL, NULL, NULL),
(212674, 'Gettysburg College', 'gettysburg-college', NULL, NULL, 61, NULL, NULL, NULL, NULL),
(195216, 'St. Lawrence University', 'st-lawrence-university', NULL, NULL, 62, NULL, NULL, NULL, NULL),
(209922, 'Reed College', 'reed-college', NULL, NULL, 63, NULL, NULL, NULL, NULL),
(148016, 'Principia College', 'principia-college', NULL, NULL, 64, NULL, NULL, NULL, NULL),
(234085, 'Virginia Military Institute', 'virginia-military-institute', NULL, NULL, 65, NULL, NULL, NULL, NULL),
(239017, 'Lawrence University', 'lawrence-university', NULL, NULL, 66, NULL, NULL, NULL, NULL),
(138600, 'Agnes Scott College', 'agnes-scott-college', NULL, NULL, 67, NULL, NULL, NULL, NULL),
(218973, 'Wofford College', 'wofford-college', NULL, NULL, 68, NULL, NULL, NULL, NULL),
(170532, 'Kalamazoo College', 'kalamazoo-college', NULL, NULL, 69, NULL, NULL, NULL, NULL),
(173647, 'Gustavus Adolphus College', 'gustavus-adolphus-college', NULL, NULL, 70, NULL, NULL, NULL, NULL),
(189088, 'Bard College', 'bard-college', NULL, NULL, 71, NULL, NULL, NULL, NULL),
(214175, 'Muhlenberg College', 'muhlenberg-college', NULL, NULL, 72, NULL, NULL, NULL, NULL),
(174747, 'College of St. Benedict', 'college-of-st-benedict', NULL, NULL, 73, NULL, NULL, NULL, NULL),
(191630, 'Hobart and William Smith Colleges', 'hobart-william-smith', NULL, NULL, 74, NULL, NULL, NULL, NULL),
(146481, 'Lake Forest College', 'lake-forest-college', NULL, NULL, 75, NULL, NULL, NULL, NULL),
(168281, 'Wheaton College', 'wheaton-college-ma', NULL, NULL, 76, NULL, NULL, NULL, NULL),
(150455, 'Earlham College', 'earlham-college', NULL, NULL, 77, NULL, NULL, NULL, NULL),
(206589, 'College of Wooster', 'college-of-wooster', NULL, NULL, 78, NULL, NULL, NULL, NULL),
(210401, 'Willamette University', 'willamette-university', NULL, NULL, 79, NULL, NULL, NULL, NULL),
(210669, 'Allegheny College', 'allegheny-college', NULL, NULL, 80, NULL, NULL, NULL, NULL),
(146427, 'Knox College', 'knox-college', NULL, NULL, 81, NULL, NULL, NULL, NULL),
(174792, 'St. Johns University', 'st-johns-university-mn', NULL, NULL, 82, NULL, NULL, NULL, NULL),
(167996, 'Stonehill College', 'stonehill-college', NULL, NULL, 83, NULL, NULL, NULL, NULL),
(152390, 'Saint Marys College', 'saint-marys-college', NULL, NULL, 84, NULL, NULL, NULL, NULL),
(163976, 'St. Johns College', 'st-johns-college', NULL, NULL, 85, NULL, NULL, NULL, NULL),
(216524, 'Ursinus College', 'ursinus-college', NULL, NULL, 86, NULL, NULL, NULL, NULL),
(228343, 'Southwestern University', 'southwestern-university', NULL, NULL, 87, NULL, NULL, NULL, NULL),
(222983, 'Austin College', 'austin-college', NULL, NULL, 88, NULL, NULL, NULL, NULL),
(184348, 'Drew University', 'drew-university', NULL, NULL, 89, NULL, NULL, NULL, NULL),
(216667, 'Washington and Jefferson College', 'washington-and-jefferson', NULL, NULL, 90, NULL, NULL, NULL, NULL),
(170301, 'Hope College', 'hope-college', NULL, NULL, 91, NULL, NULL, NULL, NULL),
(213251, 'Juniata College', 'juniata-college', NULL, NULL, 92, NULL, NULL, NULL, NULL),
(238333, 'Beloit College', 'beloit-college', NULL, NULL, 93, NULL, NULL, NULL, NULL),
(164216, 'Washington College', 'washington-college', NULL, NULL, 94, NULL, NULL, NULL, NULL),
(125763, 'Whittier College', 'whittier-college', NULL, NULL, 95, NULL, NULL, NULL, NULL),
(183239, 'Saint Anselm College', 'saint-anselm-college', NULL, NULL, 96, NULL, NULL, NULL, NULL),
(236328, 'University of Puget Sound', 'university-of-puget-sound', NULL, NULL, 97, NULL, NULL, NULL, NULL),
(140553, 'Morehouse College', 'morehouse-college', NULL, NULL, 98, NULL, NULL, NULL, NULL),
(163912, 'St. Marys College of Maryland', 'st-marys-college-maryland', NULL, NULL, 99, NULL, NULL, NULL, NULL),
(143084, 'Augustana College', 'augustana-college', NULL, NULL, 100, NULL, NULL, NULL, NULL);

-- Update existing colleges (rankings + seed metadata where available)
UPDATE colleges c
SET
    usnews_national_rank = r.national_rank,
    usnews_business_rank = r.business_rank,
    usnews_liberal_arts_rank = r.liberal_arts_rank,
    city = COALESCE(r.city, c.city),
    state_region = COALESCE(r.state_region, c.state_region),
    website_url = COALESCE(r.website_url, c.website_url),
    application_platform = COALESCE(r.app_platform, c.application_platform)
FROM _rankings r
WHERE c.scorecard_id = r.scorecard_id;

-- Insert colleges that don't already exist
INSERT INTO colleges (name, slug, country, scorecard_id,
    usnews_national_rank, usnews_business_rank, usnews_liberal_arts_rank,
    city, state_region, website_url, application_platform)
SELECT r.school_name, r.slug, 'US', r.scorecard_id,
    r.national_rank, r.business_rank, r.liberal_arts_rank,
    r.city, r.state_region, r.website_url, r.app_platform
FROM _rankings r
WHERE NOT EXISTS (
    SELECT 1 FROM colleges c WHERE c.scorecard_id = r.scorecard_id
)
ON CONFLICT (slug) DO UPDATE SET
    scorecard_id = EXCLUDED.scorecard_id,
    usnews_national_rank = EXCLUDED.usnews_national_rank,
    usnews_business_rank = EXCLUDED.usnews_business_rank,
    usnews_liberal_arts_rank = EXCLUDED.usnews_liberal_arts_rank,
    city = COALESCE(EXCLUDED.city, colleges.city),
    state_region = COALESCE(EXCLUDED.state_region, colleges.state_region),
    website_url = COALESCE(EXCLUDED.website_url, colleges.website_url),
    application_platform = COALESCE(EXCLUDED.application_platform, colleges.application_platform);

DROP TABLE _rankings;
