-- Transactional workflow handoff, using the existing notification and audit feeds.
ALTER TABLE tasks ADD COLUMN notice_revision bigint NOT NULL DEFAULT 0,
  ADD COLUMN workflow_step_id uuid REFERENCES student_workflow_steps(id) ON DELETE SET NULL;
ALTER TABLE notifications ADD COLUMN task_id uuid REFERENCES tasks(id) ON DELETE CASCADE,
  ADD COLUMN workflow_id uuid REFERENCES student_workflows(id) ON DELETE CASCADE,
  ADD COLUMN event_key text,
  ADD COLUMN event_data jsonb,
  ADD COLUMN email_state text CHECK(email_state IN ('queued','sending','sent','skipped','needs_attention')),
  ADD COLUMN email_payload jsonb,
  ADD COLUMN email_claim uuid, ADD COLUMN email_claimed_at timestamptz,
  ADD COLUMN email_first_attempt_at timestamptz, ADD COLUMN email_sent_at timestamptz;
CREATE UNIQUE INDEX task_notice_event ON notifications(firm_id,user_id,event_key) WHERE event_key IS NOT NULL;
CREATE INDEX task_notice_queue ON notifications(email_state,created_at) WHERE email_state IN ('queued','sending');
ALTER TABLE audit_events ADD COLUMN event_key text;
CREATE UNIQUE INDEX audit_event_key ON audit_events(firm_id,event_key) WHERE event_key IS NOT NULL;

-- Recipient checks are independent of the caller. Used at enqueue, feed read,
-- and delivery, so an owner/audience/membership change removes stale access.
-- PL/pgSQL gets a fresh statement snapshot, including tasks inserted by an RPC.
CREATE FUNCTION public.task_notice_allowed(p_task uuid,p_user uuid) RETURNS boolean
LANGUAGE plpgsql VOLATILE SECURITY INVOKER SET search_path=public AS $$
BEGIN
 RETURN EXISTS (
  SELECT 1 FROM tasks t JOIN firm_memberships m ON m.firm_id=t.firm_id AND m.user_id=p_user AND m.status='active'
  JOIN users u ON u.id=p_user
  WHERE t.id=p_task AND t.archived_at IS NULL AND NOT t.owner_pending
    AND u.auth_provider_user_id NOT LIKE 'invited_%' AND u.auth_provider_user_id NOT LIKE 'pending_%'
    AND p_user IN (t.assigned_user_id,t.reviewer_user_id)
    AND (
      m.role IN ('firm_owner','firm_admin','read_only_staff') OR
      (m.role IN ('counselor','essay_coach','tutor') AND (t.student_id IS NULL OR EXISTS
        (SELECT 1 FROM student_staff_assignments a WHERE a.firm_id=t.firm_id AND a.student_id=t.student_id AND a.user_id=p_user))) OR
      (m.role='student' AND t.visibility_scope IN ('student','family') AND EXISTS
        (SELECT 1 FROM students s WHERE s.id=t.student_id AND s.firm_id=t.firm_id AND s.user_id=p_user)) OR
      (m.role='parent_guardian' AND t.visibility_scope='family' AND EXISTS
        (SELECT 1 FROM students s JOIN family_members f ON f.family_id=s.family_id AND f.firm_id=s.firm_id
          WHERE s.id=t.student_id AND s.firm_id=t.firm_id AND f.user_id=p_user))
    )
 );
END $$;
REVOKE ALL ON FUNCTION public.task_notice_allowed(uuid,uuid) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.task_notice_allowed(uuid,uuid) TO authenticated,service_role;
CREATE POLICY task_notices_current_access ON notifications AS RESTRICTIVE FOR SELECT TO authenticated
  USING (task_id IS NULL OR public.task_notice_allowed(task_id,user_id));

-- Task-event payload and delivery state cannot be forged/edited through the
-- user-facing notification API. The only user edit on a task notice is read_at.
CREATE FUNCTION public.protect_task_notice() RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER SET search_path=public AS $$
BEGIN
 IF current_user IN ('postgres','service_role') THEN RETURN NEW; END IF;
 IF TG_OP='INSERT' THEN
   IF (NEW.event_key IS NOT NULL OR NEW.task_id IS NOT NULL OR NEW.email_state IS NOT NULL) AND pg_trigger_depth()<2 THEN RAISE EXCEPTION 'Task notices are generated by task transitions'; END IF;
 ELSIF (OLD.event_key IS NOT NULL OR NEW.event_key IS NOT NULL OR NEW.task_id IS NOT NULL OR NEW.email_state IS NOT NULL)
   AND (to_jsonb(NEW)-'read_at') IS DISTINCT FROM (to_jsonb(OLD)-'read_at') THEN RAISE EXCEPTION 'Only read state may be changed';
 END IF;
 RETURN NEW;
END $$;
REVOKE ALL ON FUNCTION public.protect_task_notice() FROM PUBLIC,anon;
CREATE TRIGGER protect_task_notice BEFORE INSERT OR UPDATE ON notifications FOR EACH ROW EXECUTE FUNCTION public.protect_task_notice();

CREATE FUNCTION public.bump_task_notice_revision() RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER SET search_path=public AS $$
BEGIN
 IF ROW(NEW.status,NEW.assigned_user_id,NEW.owner_pending,NEW.reviewer_user_id,NEW.due_at,NEW.needs_attention)
   IS DISTINCT FROM ROW(OLD.status,OLD.assigned_user_id,OLD.owner_pending,OLD.reviewer_user_id,OLD.due_at,OLD.needs_attention)
 THEN NEW.notice_revision:=OLD.notice_revision+1; ELSE NEW.notice_revision:=OLD.notice_revision; END IF;
 RETURN NEW;
END $$;
REVOKE ALL ON FUNCTION public.bump_task_notice_revision() FROM PUBLIC,anon;
CREATE TRIGGER task_notice_revision BEFORE UPDATE ON tasks FOR EACH ROW EXECUTE FUNCTION public.bump_task_notice_revision();

CREATE FUNCTION public.record_task_handoff() RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER SET search_path=public AS $$
DECLARE kind text; recipient uuid; key text; label text; body text; w student_workflows; actor uuid;
BEGIN
 actor:=coalesce(NEW.updated_by_user_id,NEW.created_by_user_id);
 IF TG_OP='INSERT' THEN kind:='task_assigned';
 ELSIF NEW.status IS DISTINCT FROM OLD.status THEN
   kind:=CASE NEW.status WHEN 'submitted' THEN 'task_submitted' WHEN 'changes_requested' THEN 'task_changes_requested'
     WHEN 'completed' THEN 'task_approved' WHEN 'pending' THEN 'task_reopened' ELSE 'task_progress' END;
 ELSIF NEW.owner_pending IS DISTINCT FROM OLD.owner_pending OR NEW.assigned_user_id IS DISTINCT FROM OLD.assigned_user_id THEN kind:='task_assigned';
 ELSIF NEW.reviewer_user_id IS DISTINCT FROM OLD.reviewer_user_id AND NEW.status='submitted' THEN kind:='task_submitted';
 ELSIF NEW.needs_attention AND NOT OLD.needs_attention THEN kind:='task_attention';
 ELSIF NEW.due_at IS DISTINCT FROM OLD.due_at THEN kind:='task_deadline_changed';
 ELSE RETURN NEW; END IF;
 key:='task:'||NEW.id||':'||NEW.notice_revision||':'||kind;
 INSERT INTO audit_events(firm_id,actor_user_id,entity_type,entity_id,action_type,metadata_json,event_key)
 VALUES(NEW.firm_id,actor,'task',NEW.id,kind,jsonb_build_object('label',replace(kind,'_',' ')||': '||NEW.title,'student_id',NEW.student_id,'status',NEW.status),key)
 ON CONFLICT DO NOTHING;
 IF kind='task_progress' OR NEW.owner_pending OR NEW.archived_at IS NOT NULL THEN RETURN NEW; END IF;
 recipient:=CASE WHEN kind IN ('task_submitted','task_attention') THEN NEW.reviewer_user_id ELSE NEW.assigned_user_id END;
 IF NOT public.task_notice_allowed(NEW.id,recipient) THEN RETURN NEW; END IF;
 SELECT sw.* INTO w FROM student_workflow_steps s JOIN student_workflows sw ON sw.id=s.student_workflow_id
   WHERE (s.id=NEW.workflow_step_id OR s.linked_task_id=NEW.id) AND sw.firm_id=NEW.firm_id AND sw.student_id=NEW.student_id LIMIT 1;
 IF kind='task_assigned' AND w.id IS NOT NULL AND w.status='not_started' THEN
   kind:='plan_published'; key:='plan:'||w.id||':published';
 END IF;
 IF kind='task_deadline_changed' AND w.id IS NOT NULL THEN key:='schedule:'||w.id||':'||txid_current(); END IF;
 label:=CASE kind WHEN 'plan_published' THEN 'New plan: '||coalesce(w.name,'Your plan')
   WHEN 'task_assigned' THEN 'New task: '||NEW.title WHEN 'task_submitted' THEN 'Ready for your review: '||NEW.title
   WHEN 'task_changes_requested' THEN 'Changes requested: '||NEW.title WHEN 'task_approved' THEN 'Completed: '||NEW.title
   WHEN 'task_deadline_changed' THEN 'Due date changed: '||NEW.title WHEN 'task_attention' THEN 'Work needs attention: '||NEW.title
   ELSE 'Task reopened: '||NEW.title END;
 body:=CASE kind WHEN 'plan_published' THEN 'Your plan is ready. Open your first assigned task to get started.'
   WHEN 'task_submitted' THEN 'The submitted work is ready for your decision.'
   WHEN 'task_changes_requested' THEN CASE WHEN NEW.dependency_blocked THEN 'A prerequisite reopened. Your work is saved; open the task to check what is waiting.' ELSE 'Open the task for feedback and submit the revised work.' END
   WHEN 'task_approved' THEN 'This work is complete. Open the task to see the next action and responsible person.'
   WHEN 'task_deadline_changed' THEN 'Open the task to check its updated due date.' ELSE 'Open the task for instructions and the next action.' END;
 INSERT INTO notifications(firm_id,user_id,kind,title,body,href,task_id,workflow_id,event_key,event_data,email_state)
 VALUES(NEW.firm_id,recipient,kind,label,body,'/task/'||NEW.id,NEW.id,w.id,key,
   jsonb_build_object('status',NEW.status,'due_at',NEW.due_at,'revision',NEW.notice_revision),'queued') ON CONFLICT DO NOTHING;
 RETURN NEW;
END $$;
REVOKE ALL ON FUNCTION public.record_task_handoff() FROM PUBLIC,anon;
CREATE TRIGGER task_notice_event AFTER INSERT OR UPDATE ON tasks FOR EACH ROW EXECUTE FUNCTION public.record_task_handoff();

-- Claim receipts coordinate event wakeups and periodic recovery. A retry retains
-- the same notification ID as its provider idempotency key. Never automatically
-- retry an uncertain send beyond the provider's 24-hour idempotency window.
CREATE FUNCTION public.claim_task_notices(p_limit integer DEFAULT 100) RETURNS SETOF notifications
LANGUAGE plpgsql SECURITY INVOKER SET search_path=public AS $$
BEGIN
 UPDATE notifications SET email_state='needs_attention' WHERE email_state IN ('queued','sending')
   AND email_first_attempt_at < now()-interval '23 hours';
 RETURN QUERY WITH candidates AS (SELECT id FROM notifications WHERE task_id IS NOT NULL AND
   (email_state='queued' OR (email_state='sending' AND email_claimed_at<now()-interval '5 minutes'))
   ORDER BY created_at LIMIT least(greatest(p_limit,1),200) FOR UPDATE SKIP LOCKED)
 UPDATE notifications n SET email_state='sending',email_claim=gen_random_uuid(),email_claimed_at=now(),
   email_first_attempt_at=coalesce(n.email_first_attempt_at,now()) FROM candidates c WHERE n.id=c.id RETURNING n.*;
END $$;
REVOKE ALL ON FUNCTION public.claim_task_notices(integer) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.claim_task_notices(integer) TO service_role;

CREATE FUNCTION public.enqueue_task_reminders(p_now timestamptz DEFAULT now()) RETURNS integer
LANGUAGE plpgsql SECURITY INVOKER SET search_path=public AS $$
DECLARE t record; recipient uuid; inserted integer; total integer:=0;
BEGIN
 FOR t IN SELECT task.*,coalesce(f.timezone,'America/New_York') zone FROM tasks task JOIN firms f ON f.id=task.firm_id
   WHERE task.status IN ('pending','in_progress','changes_requested','submitted') AND task.archived_at IS NULL
     AND NOT task.owner_pending AND NOT task.dependency_blocked AND NOT task.needs_attention AND task.due_at <= p_now+interval '48 hours'
 LOOP
  recipient:=CASE WHEN t.status='submitted' THEN t.reviewer_user_id ELSE t.assigned_user_id END;
  IF NOT public.task_notice_allowed(t.id,recipient) THEN CONTINUE; END IF;
  INSERT INTO notifications(firm_id,user_id,kind,title,body,href,task_id,event_key,event_data,email_state)
    VALUES(t.firm_id,recipient,'task_reminder',CASE WHEN t.status='submitted' THEN 'Review waiting: ' ELSE 'Task reminder: ' END||t.title,
      CASE WHEN t.due_at<p_now THEN 'This task is overdue. Open it for the next action.' ELSE 'This task is due soon. Open it for the next action.' END,
      '/task/'||t.id,t.id,'reminder:'||t.id||':'||(p_now AT TIME ZONE t.zone)::date,
      jsonb_build_object('status',t.status,'due_at',t.due_at,'revision',t.notice_revision),'queued') ON CONFLICT DO NOTHING;
  GET DIAGNOSTICS inserted=ROW_COUNT;total:=total+inserted;
 END LOOP;
 RETURN total;
END $$;
REVOKE ALL ON FUNCTION public.enqueue_task_reminders(timestamptz) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.enqueue_task_reminders(timestamptz) TO service_role;

CREATE OR REPLACE FUNCTION public.materialize_workflow_task(p_step uuid,p_firm uuid,p_actor uuid,p_owner uuid,p_role text,p_ready boolean)
RETURNS uuid LANGUAGE plpgsql SECURITY INVOKER SET search_path=public AS $$
DECLARE st student_workflow_steps; sw student_workflows; ts workflow_template_steps; result uuid; dependency uuid; zone text;
BEGIN
  SELECT * INTO st FROM student_workflow_steps WHERE id=p_step FOR UPDATE;
  SELECT * INTO sw FROM student_workflows WHERE id=st.student_workflow_id AND firm_id=p_firm;
  IF sw.id IS NULL THEN RAISE EXCEPTION 'Step not found'; END IF;
  PERFORM public.work_actor(p_firm,p_actor,sw.student_id);
  IF st.linked_task_id IS NOT NULL THEN RETURN st.linked_task_id; END IF;
  IF p_ready AND (p_owner IS NULL OR NOT EXISTS (SELECT 1 FROM firm_memberships m JOIN users u ON u.id=m.user_id
    WHERE m.firm_id=p_firm AND m.user_id=p_owner AND m.status='active'
    AND u.auth_provider_user_id NOT LIKE 'invited_%' AND u.auth_provider_user_id NOT LIKE 'pending_%')) THEN RAISE EXCEPTION 'Owner is not ready'; END IF;
  IF st.assigned_user_id IS NOT NULL AND p_owner IS DISTINCT FROM st.assigned_user_id THEN RAISE EXCEPTION 'Owner changed. Retry materialization'; END IF;
  IF p_owner IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM firm_memberships m WHERE m.firm_id=p_firm AND m.user_id=p_owner AND m.status='active' AND (
      m.role IN ('firm_owner','firm_admin','read_only_staff') OR
      (m.role IN ('counselor','essay_coach','tutor') AND EXISTS (SELECT 1 FROM student_staff_assignments a WHERE a.firm_id=p_firm AND a.student_id=sw.student_id AND a.user_id=p_owner)) OR
      (m.role='student' AND EXISTS (SELECT 1 FROM students s WHERE s.id=sw.student_id AND s.firm_id=p_firm AND s.user_id=p_owner)) OR
      (m.role='parent_guardian' AND EXISTS (SELECT 1 FROM students s JOIN family_members f ON s.family_id=f.family_id WHERE s.id=sw.student_id AND s.firm_id=p_firm AND f.firm_id=p_firm AND f.user_id=p_owner))
    )) AND NOT (NOT p_ready AND EXISTS (SELECT 1 FROM family_members fm JOIN students eligible_student ON eligible_student.family_id=fm.family_id JOIN users u ON u.id=fm.user_id WHERE eligible_student.id=sw.student_id AND eligible_student.firm_id=p_firm AND fm.firm_id=p_firm AND fm.user_id=p_owner AND (u.auth_provider_user_id LIKE 'invited_%' OR u.auth_provider_user_id LIKE 'pending_%'))) THEN RAISE EXCEPTION 'Owner not eligible'; END IF;
  IF st.status NOT IN ('pending','in_progress') THEN RETURN NULL; END IF;
  SELECT * INTO ts FROM workflow_template_steps WHERE id=st.template_step_id;
  dependency:=CASE WHEN st.snapshot_json IS NOT NULL THEN (st.snapshot_json->>'dependency')::uuid ELSE ts.depends_on_step_id END;
  SELECT coalesce(st.snapshot_json->>'timezone',timezone,'America/New_York') INTO zone FROM firms WHERE id=p_firm;
  IF dependency IS NOT NULL AND NOT EXISTS (SELECT 1 FROM student_workflow_steps
    WHERE student_workflow_id=sw.id AND template_step_id=dependency AND status='completed') THEN RETURN NULL; END IF;
  INSERT INTO tasks(firm_id,title,description,task_type,status,priority,visibility_scope,assigned_user_id,
    owner_role,owner_pending,student_id,due_at,created_by_user_id,updated_by_user_id,completion_mode,reviewer_user_id,due_on,due_timezone,workflow_step_id)
  VALUES(p_firm,coalesce(st.snapshot_json->>'title',st.title,ts.name),CASE WHEN st.snapshot_json IS NOT NULL THEN st.snapshot_json->>'description' ELSE coalesce(st.description,ts.description) END,coalesce(st.snapshot_json->>'taskType',ts.task_type,'workflow_step'),
    'pending',coalesce(st.snapshot_json->>'priority','medium'),coalesce(st.snapshot_json->>'visibility',ts.visibility_scope),p_owner,p_role,NOT p_ready,sw.student_id,public.plan_due_at(st.due_date,zone),
    coalesce(sw.created_by_user_id,p_actor),p_actor,coalesce(st.snapshot_json->>'completionMode',ts.completion_mode),
    CASE WHEN coalesce(st.snapshot_json->>'completionMode',ts.completion_mode)='review_required' THEN sw.created_by_user_id END,st.due_date,zone,st.id)
  RETURNING id INTO result;
  UPDATE student_workflow_steps SET linked_task_id=result WHERE id=p_step;
  RETURN result;
END $$;

-- New task audit labels can include staff-only titles; never expose them to portals.
CREATE POLICY task_audit_staff_scope ON audit_events AS RESTRICTIVE FOR SELECT TO authenticated
USING (event_key IS NULL OR (public.is_staff() AND EXISTS (
 SELECT 1 FROM tasks t JOIN firm_memberships m ON m.firm_id=t.firm_id AND m.user_id=public.current_user_id() AND m.status='active'
 WHERE t.id=audit_events.entity_id AND t.firm_id=audit_events.firm_id AND (
   m.role IN ('firm_owner','firm_admin','read_only_staff') OR
   (t.student_id IS NULL AND public.current_user_id() IN (t.assigned_user_id,t.created_by_user_id)) OR
   EXISTS(SELECT 1 FROM student_staff_assignments a WHERE a.firm_id=t.firm_id AND a.student_id=t.student_id AND a.user_id=m.user_id)
 )
)));
